
spring:
  application:
      name: USER-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/na9user
    username: postgres
    password: Service@360
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  openapi:
    dev-url: http://localhost:8080
    prod-url: https://bezkoder-api.com



jwt:
  secret: ElX2k8ifx9Vq8L7rGdLLEkLomyV0P1VR
