server:
  port: 9090

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/USER-SERVICE/**
          filters:
            - RewritePath=/USER-SERVICE/(?<remaining>.*), /$\{remaining}

        - id: vehicle-service-route
          uri: lb://VEHICLE-SERVICE
          predicates:
            - Path=/VEHICLE-SERVICE/**
          filters:
            - RewritePath=/VEHICLE-SERVICE/(?<remaining>.*), /$\{remaining}



