server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false  # Server does not register itself with Eureka
    fetchRegistry: false  # Server does not need to fetch registry from another Eureka
  server:
    enable-self-preservation: true  # Enable self-preservation mode
    renewal-percent-threshold: 0.49 # Example: adjust renewal threshold
    renewal-threshold-update-interval-ms: 30000 # Example: adjust threshold update interval
    expected-response-time-ms: 1000 # Example: adjust expected response time

spring:
  application:
    name: EUREKA-SERVER
