name: CI/CD Pipeline

on:
  push:
    branches:
      - karththi 
  pull_request:
    branches:
      - karththi 

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        ports:
          - 5433:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: na9user
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build Docker Image
      run: docker build -t myapp .

    - name: Run Tests
      run: |
        docker run --network host myapp mvn test

    - name: Push Docker Image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker tag myapp "${{ secrets.DOCKER_USERNAME }}"/myapp:latest  
        docker push "${{ secrets.DOCKER_USERNAME }}"/myapp:latest      

    